### ISSUE TITLE
Support Keyboard Navigation

### ISSUE THREAD

**Issue by lauriejones** [fisshy/react-scroll#262]
Morning!

We are having a little trouble making our scrollTo links work from the keyboard. We could be doing something wrong, but as far as I can tell all scroll related events happen based off of `onClick`. It would be nice for keyboard users to also support keyDown/keyUp of the enter key and possibly the space key.

Is this something that you do or are looking to support?

Thanks,
Laurie

**Comment by fisshy** [comment]
Good morning, 

There's no support at the moment, what you could do is to create your own Link component and add this functionallity into it.

**Comment by lauriejones** [comment]
Okay, sure. Thanks for getting back to me. 👍

**Comment by fisshy** [comment]
@kylemh I welcome any PR :)

**Comment by nielsboecker** [comment]
Even though this issue is closed, I'd like to document how I've solved this issue without a custom Link component.

```typescript
import { Link, scroller, ... } from "react-scroll";

<Link
  tabIndex={0} // Required to make <a> without href focusable
  onKeyUp={(event) => {
    if (event.key == "Enter") {
      scroller.scrollTo(to, {});
    }
  }}
  ...
/>
```

Furthermore, I've sent the focus to the targeted element after scrolling (see https://github.com/fisshy/react-scroll/issues/211#issuecomment-789910232).

**Comment by kylemh** [comment]
Yikes. I'll come back to this this weekend. Sorry for the 2.5 year delay 😂

**Comment by kylemh** [comment]
I spent a bunch of time looking into a11y practices around a "scroll-to-top" sort of button, and couldn't find anything.

https://www.digitala11y.com/scrollbar-role/

Since this library doesn't have context of the whole app there's not much we can solve from the library's perspective besides advising in documentation.

I hesitated to make any changes to the codebase because Link currently has no defaults set. 

I think @nielsboecker's example is probably best, I might also add `role="button"`. I'd also recommend using [@reach/visually-hidden](https://reach.tech/visually-hidden) to supply a hidden, but rendered text representation of any scroll button that may only rely on iconography or an image.

Lastly, and the most difficult, you'd need to manage the change of applied focus depending on where somebody would scroll to. For example, imagine tabbing to the Link and hitting enter. You're taken 1000px up. When the user hits tab again, I would think they'd expect to focus onto the next focusable element in there view.

@fisshy lemme know if I can add all of this to the README.
