### ISSUE TITLE
Anchor Links not working in IE9

### ISSUE THREAD

**Issue by tonydiaz** [fisshy/react-scroll#40]
Scroll doesn't work either but for this issue just looking to make the anchor links work.

Can be tested against the example you provide:
http://fisshy.github.io/react-scroll-example/basic/index.html

**Comment by fisshy** [comment]
Sorry for the late answer, will look into it.

**Comment by goldhand** [comment]
MS stops supporting IE 8, 9, & 10 https://support.microsoft.com/en-us/kb/3123303  :)))))

**Comment by cbravo** [comment]
This is actually caused by this plugin relying on using setTimeout to pass params to a callback function in browsers that do not have requestAnimationFrame()  in the file animate-scroller.js and this is known not to work in IE which is why you are seeing that behavior.   

This stackoverflow lead me to my working solution: 
http://stackoverflow.com/questions/12404528/ie-parameters-get-undefined-when-using-them-in-settimeout

also referenced in that stack overflow is the MDN docs: 
https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout

**Comment by cbravo** [comment]
I know the response is a little late but I was working on a project that uses this lib and has to support ie9  so I thought this would be helpful to those who have had the same struggle.

**Comment by fisshy** [comment]
Ah sweet. thanks for the solution, good to know If i stumble upon this myself =). Thanks!

**Comment by kifahhk** [comment]
@cbravo can you please publish your solution.
I am still getting the same error for smooth scrolling in IE, even after implementing the Polyfill. 

- error line: requestAnimationFrame(animateTopScroll)

Thanks

**Comment by cbravo** [comment]
For my project I used the solution mentioned here: 
https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout

 I included this script below on my index.html file ** before**  including the JS for my react application and that completely solved my problem for ie9

**Comment by kifahhk** [comment]
Thanks
