### ISSUE TITLE
Images loading are causing scroll height to be off.

### ISSUE THREAD

**Issue by iDVB** [fisshy/react-scroll#85]
Is there a solve for this common issue?

Seems like by default the scroll height is calculated before all the images are loaded with is causing the scroll to be off, sometimes by alot.

**Comment by fisshy** [comment]
You are right, one future solution should be to calculate it on scroll.

You can use DirectLink with element id to scroll. See the readme file :)

**Comment by SudoPlz** [comment]
I've got the same problem, only it manifest in a different way. Scrolling does not make a class active at the right time. Thats because I've got background images within my elements, and the rect size is calculated before those images load up. What can I do to get correct rectangle calculation and thus correct active class activation?

Thanks

**Comment by fisshy** [comment]
I think this PR will solve your issues, I just haven't had time to validate it yet. 

https://github.com/fisshy/react-scroll/pull/115

**Comment by SudoPlz** [comment]
@fisshy I just added a very simple pull request that fixes my issue here https://github.com/fisshy/react-scroll/pull/126. It's just a few lines of code you can review it ultra  fast, its very straight forward.

**Comment by beautyfree** [comment]
Actual problem

**Comment by iDVB** [comment]
Unable to verify now, as we've moved on. 
Maybe someone else can?

**Comment by kand617** [comment]
This is still an issue... Anyone has a solution?
