### ISSUE TITLE
Unknown props spy, smooth, duration on <a> tag

### ISSUE THREAD

**Issue by white87332** [fisshy/react-scroll#94]
Hi, I get a warning when I update my react version to 15.2.0.
```
Warning: Unknown props `spy`, `smooth`, `duration` on <a> tag. Remove these props from the element
```

I use "Link", "Element" to scroll my screen. 

Thank you.

**Comment by philarr** [comment]
React 15.2.0 now gives off warning for attributes that are not on the whitelist 

The helper's render return should pass on props that are needed instead of everything.
https://github.com/fisshy/react-scroll/blob/master/modules/mixins/Helpers.js#L158
to
`return React.createElement(Component,  { className: className, children: this.props.children, onClick: this.handleClick });`

https://github.com/fisshy/react-scroll/blob/master/modules/mixins/Helpers.js#L177
to
`return React.createElement(Component, this.props.children);`
